name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        psabi: [default]
  
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 512
        remove-dotnet: 'true'
        remove-android: 'true'

    - uses: actions/checkout@v3

  ubuntu:
    name: Build base sysytem
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Update repository
      run: sudo apt-get update -y
    - name: Install the basic dev packages
      run: sudo apt-get install -y cmake equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++ libncurses5 libncurses5-dev make zlib1g-dev unzip traceroute tree
    - name: Set config
      run: cp system/C_CONF ./.config
    - name: Initializing the kernel
      run: |
        cd kernel/
        wget https://packages.lingmo.org/lingmo/kernel/kernel.tar.xz
        cd ..
    - name: Build System
      run: make
    - name: Done Build
      run: |
        ls output
        tree output
